### ISSUE TITLE
tolerations is not defined in deploy/kubernetes/wavefront-operator.yaml

### ISSUE THREAD

**Issue by tayken-wp** [wavefrontHQ/wavefront-operator-for-kubernetes#328]
### Problem Description
Kubernetes integration setup first applies [deploy/kubernetes/wavefront-operator.yaml](https://raw.githubusercontent.com/wavefrontHQ/wavefront-operator-for-kubernetes/main/deploy/kubernetes/wavefront-operator.yaml) file, than configures it by applying another YAML file. An example YAML file for setting up tolerations is given [here](https://github.com/wavefrontHQ/wavefront-operator-for-kubernetes/blob/main/deploy/kubernetes/scenarios/wavefront-daemonset-pod-tolerations.yaml). However, when I tried to apply it to our clusters, I got the following error message:
```
error validating data: ValidationError(Wavefront.spec.dataCollection): unknown field "tolerations" in com.wavefront.v1alpha1.Wavefront.spec.dataCollection; if you choose to ignore these errors, turn validation off with --validate=false
```
I can see that tolerations was added in #315 but [deploy/kubernetes/wavefront-operator.yaml](https://raw.githubusercontent.com/wavefrontHQ/wavefront-operator-for-kubernetes/main/deploy/kubernetes/wavefront-operator.yaml) file was untouched.

Just to test it out, I copied the tolerations definition from [config/crd/bases/wavefront.com_wavefronts.yaml](https://github.com/wavefrontHQ/wavefront-operator-for-kubernetes/blob/main/config/crd/bases/wavefront.com_wavefronts.yaml) to [deploy/kubernetes/wavefront-operator.yaml](https://raw.githubusercontent.com/wavefrontHQ/wavefront-operator-for-kubernetes/main/deploy/kubernetes/wavefront-operator.yaml). It resolved the validation error I mentioned above but didn't actually deploy the pods to the nodes.

**Comment by priyaselvaganesan** [comment]
@tayken-wp, we have not released the feature being developed on [PR#315](https://github.com/wavefrontHQ/wavefront-operator-for-kubernetes/pull/315) yet. Please wait for the next release for the tolerations to work as intended. After the next release, if you still have concerns please re-open this issue with added context.
